### ISSUE TITLE
Gem "die" at collapse...

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#123]
Could have the gem fade out (stop shining) at collapse and then start shining again after a wind. Is this a simple thing?

**Comment by silkymesmeriser** [comment]
Sure, quite easily in fact since I made both the glow and the light a setting it's just a case of modifying the test slightly to the following:

```
primLight & ~collapsed
primGlow & ~collapsed
```

There seems to be a bug with primLight currently anyway so going to flag this as a bug for that and can add the second part to the test when I go to fix it.

**Comment by silkymesmeriser** [comment]
This got fixed with the fix for `primLight`
