### ISSUE TITLE
Move lock code failing to activate

### ISSUE THREAD

**Issue by silkymesmeriser** [emmamei/cdkey#125]
This issue is almost certainly linked to issue #120, and also to situations such as the other day where the key seemed to have me carried by Dark when it was not showing it.  The problem is probably with the initially elegant and clever usage of `keyAnimation` as a proxy for much of the state information which has (with future development) become a complex mess of different tests and exceptions as well as leaving no fewer than three scripts importing full-length key and string variables - simply to determine two boolean states.
- Is doll posed?
- Is doll self posed?

This and the complex sticky tape is poor design, while it seemed to be working, I was rather loath to risk attempting to resolve the wider issues - the former excuse now gone, I think this bug should be addressed by starting internally in `Avatar` with a multi-value `dollState` variable; they are all actually simple boolean true/false states that can occur in combinations in much the same way as avatar states. In general, it seem to me that the model solution to this issue for consistency and clean code is already one that we are actually making limited use of in the code of `Main.lsl`

http://wiki.secondlife.com/wiki/LlGetAgentInfo

_Implement `cdGetDollState()`_

The other alternative is probably to break up the entire code sharing group, but were we to do so, then it is fairly likely that 2-3 entire scripts would need to be provided for them as the code share by all 4 is 24kB, and three sharing accounts for around another 10kB broken apart would have to bank on that being around 126kB excluding communication (unknown) and base script overhead (seems to be around 4096 bytes).

**Comment by emmamei** [comment]
I thought there was a variable `posed`; why not add `selfPosed` to that? In fact, I'd say that a bitmap variable called `posedBy` might be good.

I'm not in favor of bitmapped variables as a rule; it converts _every_ access from this:

```
myStateVariable
```

to this:

```
myBitmapVariable & SOME_OPT
```

and conditionals go from this:

```
inThisState && inThatState || inOtherState
```

to this:

```
(myBitmapVariable & THIS_STATE) && (myBitmapVariable & THAT_STATE) || (myBitmapVariable & OTHER_STATE)
```

In short, you trade space for increased complexity at every access.

Depending on the usage, you might even increase space requirements: instead of three variables and two operators above, you have four variables and five operators - including three sets of parenthises...
