### ISSUE TITLE
Developer Keys now require a complete script not needed in normal keys

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#136]
A developer key is a _testing_ key ... not a new item to be developed and marketed independently. It is supposed to _test_ a normal key and _debug_ a normal key... not require so much code that it requires its own debugging and git repo and the rest.

When one spends more time debugging developer and testing code than actually developing the _product_ something is wrong...

**Comment by silkymesmeriser** [comment]
This is a side effect of LSL and it's memory limits we can't justify on current SL shipping half a script just so that it has enough memory to compile, with extra code in dev mode it is not acceptable.  It is also not a requirement it is only needed to listen in on extra information as and when needed and can simply be set to not running or deleted otherwise.

**Comment by emmamei** [comment]
Code was added to make debugSay work without needing an extra script. The actual original purpose of `LinkListen.lsl` is now taken by `Transform.lsl` - which more or less happened by accident.
