### ISSUE TITLE
Is lowScriptMode needed?

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#143]
There is a `SIM_FRIENDLY` define which activates the "SIM-friendly" features of the key at compile time; the `lowScriptMode` appears to activate these same features at run time. This would only be necessary if the key has the ability to shift into a low-impact mode dynamically or by user request. The latter does not seem to be present.

**Comment by silkymesmeriser** [comment]
Confirmed, the function of this still needs to be restored it was temporarily disassembled as the changes in the code at the time were not properly reflected in the functionality of it. It dropped on the priority list for a while as the code was running pretty efficiently and not using that much time anyway but with the key regularly operating at around 3 times the script time usage than it was doing at the time it's something I do need to try and get to look at again sometime.

**Comment by emmamei** [comment]
I dont think we need either actually: either a `SIM_FRIENDLY` or a `lowScriptMode`; the Key should be reasonably Sim friendly all the time, and without a user setting or unsetting.

**Comment by silkymesmeriser** [comment]
It was never a user setting it was an automatic response to indicators of severe sim lag such as time dilation dropping and staying down.  When sim time dilation drops bellow about 0.95 then reasonably friendly would be a max of 2.5-3microseconds per object unless in a directly user interactive situation  certainly the key currently idles far too high to qualify.  We could have got away with it perhaps when we were <5 typically but while it was stable at that level from Dec-March or so it went up sharply since.

**Comment by emmamei** [comment]
As I understand it, `lowScriptMode` then was part of an automated slow-down process in the Key in response to severe lag in the sim environment. This sounds like an extreme feature, and I don't know that we need it. In any case, it can be enabled or disabled at will.
