### ISSUE TITLE
Carry button appears for Doll

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#157]
When the Doll brings up main menu, the `Carry` button is present. Expected result is for `Carry` button to appear to everyone _except_ Doll.

**Comment by silkymesmeriser** [comment]
This is only true if the doll is a builtin controller which grants full access to all controller functions with high priority overriding most conditions that would otherwise enable a builtin controller to be blocked from accessing a feature by some set of conditions or other.

Granted the Carry one is the black sheep of the group given that for technical reasons it is not possible for it to actually work for the doll themselves one way or the other.  That said is this an issue of such massive significance that for this one extremely narrow case affecting currently a sum total of 4 users closely tied to the key and aware that they are in possession of unusual access that it justifies singling out this variable not only from every other option or setting or button in the key but also from the subset of options which are affected by the builtin controller privilege.

Personally when I first became aware of this some months back I didn't really think it was worth singling it out and making it the only option where builtin controller status is pre-empted by some other limitation including being the doll wearing the key being accessed.

**Comment by emmamei** [comment]
According to the code, this is the section that determines if the user is one that can carry:

```
 if (!collapsed && ((numControllers == 0) || (isController && !isDoll))) {
```

That breaks down as the following: Dolly is...
- not collapsed, and...
- either has no controllers, or...
- is a controller, but not the dolly.

Thus, according to this, if there are no controllers, then anyone can carry the dolly - including the dolly themselves.

Perhaps a better conditional is:

```
if (!collapsed && !isDoll) {
```

This is because the Dolly themselves should never see the `Carry` button - not even as Controller, nor without any Controllers.

**Comment by emmamei** [comment]
That entire section is only done if `!collapsed` is true; therefore that code was optimized out. The posited code will be implemented and tested.

**Comment by emmamei** [comment]
Seems to be working. Closed.
