### ISSUE TITLE
RLV.lsl is missing from repository

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#17]
All files must be added to repository. The repository must be a full functioning copy of all files needed for the key to work.

**Comment by silkymesmeriser** [comment]
It's there but it's only on the development branch not main as the file did not exist when we created the branch.

If you check the current version of the repository on the server you can see it there with the commit from three days ago.
https://github.com/emmamei/cdkey/tree/Development

I do need to push some changes though as I have done quite a bit of work on it since then including setting up actual RLV command phrasing and state tracking of active restrictions and exceptions tracked by script, granted this is probably not essential to have yet but it will be useful for addons or if we get to the point that we end up having to split the RLV script itself to make sure that restrictions don't get lifted early.

I have just made some pretty large changes on the one I am running at the moment and I am not convinced there isn't a few regressions still hidden about at the moment, combined with the fact a couple of things I added I've not been able to run by you yet.  At the moment I am trying to slow down a little and do a stability phase just to tidy up the bit's I've overhauled so far and deal with any little issues that have come up then before committing it to the mainline development branch.

**Comment by emmamei** [comment]
Excellent.
