### ISSUE TITLE
New mode: Child Key

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#25]
Before a real Child Key can be released it should be made "child-safe" through some mechanism. Most likely, there should be some sort of setting - or different code - that can be set inside the code and not changeable by the user.

Most importantly, the Pleasure Doll, Slut Doll, and Stripping functions should be removed. There are almost certainly more.

This could be managed on a UNIX system with a tool like m4.

**Comment by silkymesmeriser** [comment]
I am working on this some now though I have decided to just work with simple preprocessor directives for it, the ones I am working with are fully compatible with the Firestorm LSL preprocessor but I know you like to develop outside of SL some too so you will be pleased to know that they work happily with cpp also.  In fact when it comes to doing the preprocessor run for an actual release I'm inclined to go with using cpp.

The reason being is that the FS preprocessor has no option to no strip the comments from it's output, cpp however does.

I tested with
cpp -C -nostdinc <file> | sed 's/^#/\/\//'

And it works fine, the pipe through sed is needed because cpp adds a couple of comments that indicate the source of included code and it uses # style which is valid in C but not in LSL.  Quick run through sed makes that a none issue however.  We could use m4 or something but I think for what we need it might be a bit of overkill when a couple of simple preprocessor directives will do the trick.

At the moment those I have so far are all just
#include
#define
#ifdef
#else
#endif

Course the advantage of doing it this way over any other is that if we use this for the child key then the code for those features won't just be disabled and of course with any way of disabling it there is always some way it could become undisabled.  If it is stripped by the preprocessor before we even upload it however it simply isn't there, of course so long as the object is mod and there are adult versions available there would be nothing at all to stop someone stripping an adult one and swapping the scripts.

Should be the best way to keep us secure from any liability for it though after all there would be no risk of us introducing a bug that allowed access to a feature that should not be there as no bug can enable non existent code.  Were anyone to go to the effort of moving the scripts around and stuff we could also show that we have done everything reasonably in our power to prevent such for that model short of violating our own licence (I'm guessing we are working on something along the lines of the GPL?)

**Comment by emmamei** [comment]
I was thinking about that - about actually having the relevant code stripped entirely. However, it does mean one thing that I dont like: up until this point, the entire repository could be copied into the Key and used. With a preprocessor, it means that the code must be processed before being used.

I'm not sure that is avoidable - if we're to make a child key that has no unexpected behaviors, then it may be necessary.

I suspect that cpp was used as a model - but in recent years, cpp has been getting eliminated - specifically, gcc eliminated it as a standalone program a while ago I thought. It does exist in MacOS X however. If we use cpp - a Makefile would also be appropriate so we can build the LSL script to be used by the Key.

**Comment by silkymesmeriser** [comment]
I'm less familiar with make I was going to write a simple shell script in a scripts sub directory for this.  Possibly adding a simple run through awk to filter out long sequences of blank or whitespace only lines left over from the preprocessor.

**Comment by emmamei** [comment]
`make` handles dependencies and should be known by any developer. If you change the code, then the dependent result is regenerated - but not unless necessary: very useful for C programming projects and so on.

Shouldn't be any white-space left over - but for pre-processing I'm biased towards `m4` but it's not used like it once was - then again, `cpp` isn't used either: it's been absorbed into the compiler.

**Comment by silkymesmeriser** [comment]
The reason I've gone with cpp style directives is they are fully compatible with firestorms internal LSL preprocessor also.

**Comment by silkymesmeriser** [comment]
Probably because of the fact that FS is itself written in C so the dev who wrote it probably used what they knew.

**Comment by emmamei** [comment]
I'll be starting to code with the preprocessor then - and will probably make some significant changes. I hope that doesn't conflict with what you are doing: the changes will hide the inefficiencies of LSL that lead to space savings and so on.

I'll implement changes for readability and for debugging.

**Comment by silkymesmeriser** [comment]
I've managed to fix the regressions I had this end I think so let me commit what I have before we end up duplicating each others efforts

**Comment by emmamei** [comment]
My initial try at the preprocessor didn't work... the results were quite odd - segments of code were missing...

**Comment by silkymesmeriser** [comment]
I can try and help you with it at some point though for things like that and a few other things we could do with discussing sometimes it would be easier to do "live" than through back and forth in comments.

**Comment by emmamei** [comment]
The GNU cpp documentation has this:

```
       The C preprocessor is intended to be used only with C, C++, and Objective-C source code.  In the past, it has been abused as a general text processor.  It
       will choke on input which does not obey C's lexical rules.  For example, apostrophes will be interpreted as the beginning of character constants, and
       cause errors.  Also, you cannot rely on it preserving characteristics of the input which are not significant to C-family languages.  If a Makefile is
       preprocessed, all the hard tabs will be removed, and the Makefile will not work.
```

and also this:

```
       Wherever possible, you should use a preprocessor geared to the language you are writing in.  Modern versions of the GNU assembler have macro facilities.
       Most high level programming languages have their own conditional compilation and inclusion mechanism.  If all else fails, try a true general text
       processor, such as GNU M4.
```

I imagine neither of us will be using the FS preprocessor - and your script has to "clean up" the output from cpp as it is.

Your script also regenerates _every_ script _every_ time: using `make` allows you to only generate output for those files that have actually changed.

I recommend using `make` and `m4` - both are generally available in UNIX environments.

**Comment by emmamei** [comment]
Using `Firestorm` and its variant of `cpp` have taken root, and seems to work fine. The last vestiges of `make` and `autoconf` have been removed.
