### ISSUE TITLE
Using cpp or make and m4 to preprocess code

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#39]
Do we use `cpp` or do we use `make` and `m4`? The `cpp` man page specifically recommends _not_ using it for languages other than the C family of languages.

This was brought up in issue #25.

**Comment by silkymesmeriser** [comment]
I've been using cpp because it is compatible with the internal preprocessor in firestorm m4 in not.

You know it might be worth trying to find out exactly how the firestorm LSL preprocessor actually works I notice it writes files to disk under ~/.firestorm/cache/lslpreproc first which seriously makes me wonder if it might actually be calling one or more third party binaries to do it the work.

**Comment by silkymesmeriser** [comment]
LSL uses C syntax also thus why cpp is working with it.

**Comment by silkymesmeriser** [comment]
To your point over on #25 about neither of us using the internal preprocessor, well actually I have done since phoenix first included one as I was already working on several larger complex projects which benefited from it if you have seen one or two of the scripts I did for Minako I forgot to turn it off on them so they have the preprocessor comments in them.

I wouldn't use it for the final product as cpp seems to produce cleaner output the internal preprocessor leaves a lot of excess whitespace etc.  But for development it works great because you don't have to sit there over and over again reuploading every few minutes to unit test things as you go along.

**Comment by emmamei** [comment]
Sticking with cpp does seem to be appropriate. However, using the shell scripts is not a good practice, nor is including the processed code in the repository.

This is brought up in issue #40 - and changes are completed locally.
