### ISSUE TITLE
Current cpp files corrupt main source

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#41]
When run with GNU cpp, the source code is completely corrupted. The problem lies in the comments on the `#define` lines.

The cpp used is:

```
emd$ cpp --version
i686-apple-darwin10-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5659)
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

The problem is that the `#define` is taken in three parts: 1) `#define` keyword; 2) macro name; 3) macro definition. There is _no_ comment there - and in this instance, it is taken as part of the macro definition. This leads to complete corruption as everything after the desired definition is wiped out in a comment.

For instance, this line:

```
#define SEC_TO_MIN 60.0                                         // Seconds per minute
```

results in this code being generated:

```
float windamount   = 1800.0; // 30 * 60.0                                         // Seconds per minute;    // 30 minutes
```

This is why the FS preprocessor appeared to be corrupting things - because of these comments.

This also shows that there was no testing or trial runs with this code before submission to the repository. A repository with syntax errors is unacceptable.

I've fixed this and will submit it to the repository along with the makefiles and directory restructure shortly.

**Comment by silkymesmeriser** [comment]
Interesting because I did test this and it worked completed fine here on linux as it was or I'd have not committed it that way so no it's not because it wasn't tested but seems to be down to a difference between systems.  Given that FS uses the same basic preprocessor functionality that Phoenix had and there has been no real changes on that front that I know of for a long time certainly not between the latest release version which you have and the beta version I am running.

Which would appear to make a difference in `cpp` the most likely suspect to cause this one that it affects firestorms internal preprocessor also would seem to also be supportive of my theory that FS either uses `cpp` as an external program of at the very least is executing some point of it is's code in reality of course it is probably making use of one or more shared objects that are components of the C preprocessor and/or C compiler or both thereof given they are part of the same package chances are they have at least one soname in common.

I just checked both the system FS runs on:

```
~ $ cpp --version
cpp (Gentoo 4.7.3-r1 p1.3, pie-0.5.5) 4.7.3
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

And the local version on the laptop which I also used for development with the way it was before and has no problems.

```
~/git/cdkey $ cpp --version
cpp (Ubuntu/Linaro 4.8.1-10ubuntu9) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Both of which are a significant difference to the version your system has installed 4.2.1 note also the specified copyright dates, for the laptops install of 4.8.1 it's showing 2013, the desktops install of 4.7.3 is reporting 2012.  Seems the source for the binary installed by apple there was last updated or at least had it's copyright notice last updated back in 2007 so if that is even remotely accurate then it is not inconceivable that something could well have changed

Actually I just had a look in the repository for the Gentoo machine because gcc and the rest of that stuff is a slotted package (meaning it supports multiple simultaneously installed versions) and it turns out that there is a slot for gcc-4.2 still in the repository though it's 4.2.4-r1 not 4.2.1 anyway have it building now see if I can get the same result with that selected once installed.

Either way won't use that style anymore but would be interesting to confirm the exact cause of the issue.
