### ISSUE TITLE
Debug "complete avi changes" with +folders

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#6]
Using a + folder is supposed to be sufficient to completely reset the avi - to allow full avi outfits with the Key. This is not sufficiently tested and it doesn't seem to currently work.

**Comment by silkymesmeriser** [comment]
This is strange as it would go against the standard convention, the plus prefix is used for two things:
- One to indicate an optional subpart of another outfit.
- Two as part of the RLV standard to indicate to the viewer that the contents of this folder should add not replace unless explicitly given a command that states otherwise.

**Comment by emmamei** [comment]
This capability predates my work with the key - it apparently was designed to have complete avis stored as outfits. Not sure if this ever worked right at all.

**Comment by silkymesmeriser** [comment]
I have come up with an alternative solution to this idea using the new > folders as a basis.

Basically a folder with a !> prefix that then chroots the path to ~normalself etc upon entering it.

This will also work with no copy avatars etc too as they only need to be stored once no matter how many outfits you have for that avatar.

**Comment by emmamei** [comment]
Did we decide to not use the `+folder` setup at all?

**Comment by emmamei** [comment]
The "complete avi changes" seems to be a removed feature; this is not necessarily a bad thing because folders with plus names (`+Folder`) were used for a different purpose in standard RLV and OpenCollar operations.
