### ISSUE TITLE
FS Animations triggered during sit

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#60]
When sitting, and FS AO is off - winding triggers a turning on of the FS AO which messes up the sit pose. This requires the user to turn FS AO off again.

**Comment by emmamei** [comment]
Doing a self-wind during a dance did not trigger this: FS AO remained off, through entire complete windup.

**Comment by emmamei** [comment]
Investigating further, this happened after a collapse (I missed it - was AFK). Is this a _wontfix_ ?

**Comment by silkymesmeriser** [comment]
Unfortunately there is no way to my knowledge to query the AO's current state so this we can't note it's state before turning it off and then restore it after which would be the ideal.  That would be a Firestorm limitation though rather than anything we can do anything about.

The case with sitting is interesting and perhaps there are some options there like delaying the handling of any animation stuff while `((llGetAgentInfo & AGENT_SITTING) != 0)` not sure exactly at the moment but will leave this report open and try to investigate at some point.

**Comment by emmamei** [comment]
I think I saw this "problem" show up with something else - I forget what - but something unrelated to the Key. May just be "one of those things" that you learn to live with.
