### ISSUE TITLE
Check and verify proper script startup process

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#8]
The start up process of a script includes state_entry, on_rez, and attach.... and they get triggered asynchronously, and at different times and for different reasons.

Check what runs and when - and make sure its in the right slot.

**Comment by silkymesmeriser** [comment]
I have assigned myself on this because I have been working on this as part of the work I have been doing my next commit also features a change to the state entry events so that now if a script is reset it re-initializes everything in a predictable order.

Was needed due to the issue that to keep them in sync a reset of Main needs a reset of RLV and the other way is true also but simply putting reset in both is an infinite loop.

**Comment by emmamei** [comment]
What is the status of this? If it's good and done then we can close the ticket.

**Comment by silkymesmeriser** [comment]
I think this is finished at least I am certain enough to close this, should any other issues arise a more specific bug could be raised anyway in place of this general one.
