### ISSUE TITLE
Detach button seems to be ineffective

### ISSUE THREAD

**Issue by emmamei** [emmamei/cdkey#89]
Trying to detach the Key using the `Detach` button does nothing.

**Comment by silkymesmeriser** [comment]
This one appears to have been caused by a third party bug or network issue, RLV debug output at the time showed that the dolls Firestorm viewer did indeed receive the `@clear,detachme=force` command which it claims to have executed however no detach was forthcoming.

This seems to leave 4 possibilities:

**Firestorm never executed the command despite the debug message saying so.**
- In retrospect this one is looking unlikely I took the time to look at the actual viewer logfiles from ~/.firestorm/logs for the session in question and admittedly decoding those viewer logs is a science in itself but from what I can see there are messages in there which appear to indicate that the viewer did execute the RLV correctly and I believe did indeed put the detach message on the wire.

**Packet loss or transient network failure**
- Course the reality of it is the viewer doesn't put things on the wire it gives them to the operating system which is then supposed to put them on the wire and then hopefully all being well the network successfully route that to the destination host pass all of it's hardware and OS checks to actually be delivered to the application layer.

**Simulator error**
- This is where the real work of the detaching is done and it can and does sometimes go wrong, though in all truth the simulator tends to be at fault more often when attaching than when detaching which is a simpler operating for it provided of course that it can reach.

**The asset server (well cluster)**
- Detaching is a bigger load on this heavily hit group of systems than even attaching as attaching is merely a retrieve (When attaching an object from inventory, an object newly created in world being attached from the ground is a create as the asset only gets saved to the central asset server when taken into inventory which occurs as part of attaching it), detaching on the other hand is an update.

Anyway in this case I think that this can be closed I see nothing much more we can do in any case.
